apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt
  name: chat-frontend
  namespace: swiss-ai
spec:
  ingressClassName: nginx
  rules:
  - host: chat.swissai.cscs.ch
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: chat-frontend-internal
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - chat.swissai.cscs.ch
    secretName: chat-cert # < cert-manager will store the created certificate in this secret.